# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mineru
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  workflow_dispatch:
jobs:
  pdf-test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: true

    steps:
    - name: PDF benchmark
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: check-requirements
      run: |
        pip install -r requirements.txt
        pip install -r requirements-qa.txt
    - name: get-benchmark-result
      run: |
        echo "start test"
        echo $GITHUB_WORKSPACE
        tree
        cd $GITHUB_WORKSPACE && python tests/benchmark/benchmark.py
  
