# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PDF
on:
  push:
    branches:
      - master
    paths-ignore:
      - "cmds/**"
      - "**.md"

jobs:
  pdf-test:
    runs-on: pdf
    timeout-minutes: 40
    strategy:
      fail-fast: true

    steps:
    - name: PDF benchmark
      uses: actions/checkout@v3

    - name: check-requirements
      run: |
        changed_files=$(git diff --name-only -r HEAD^1 HEAD)
        echo $changed_files
        if [[ $changed_files =~ "requirements.txt" ]]; then
          pip install -r requirements.txt
        fi


    - name: benchmark
      run: |
        echo "start test"
        python ocr_badcase.py pdf_json_label_0306.json ocr_dataset.json json_files.zip output.json
