# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mineru
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  workflow_dispatch:
jobs:
  cli-test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: true

    steps:
    - name: PDF cli
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
      
    - name: check-requirements
      run: |
        pip install -r requirements.txt
        pip install -r requirements-qa.txt
    - name: test_cli
      run: |
        cp magic-pdf.template.json ~/magic-pdf.json
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE && export PYTHONPATH=. && pytest -s -v tests/test_unit.py
        cd $GITHUB_WORKSPACE &&  pytest -s -v tests/test_cli/test_cli.py
                                                                                                                            
